---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: tenants
  namespace: flux-system
spec:
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
  dependsOn:
  - name: kyverno-policies
  interval: 5m0s
  serviceAccountName: kustomize-controller
  path: ./tenants/staging
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
