apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: blue-team
  namespace: blue-apps
spec:
  interval: 1m
  url: https://github.com/larsdbr/k8s-tenant-blue
  ref:
    branch: main
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: blue-team
  namespace: blue-apps
spec:
  serviceAccountName: blue-team
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: blue-team
  prune: true


