apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: red-team
  namespace: red-apps
spec:
  interval: 1m
  url: https://github.com/larsdbr/k8s-tenant-red
  ref:
    branch: main
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: red-team
  namespace: red-apps
spec:
  serviceAccountName: red-team
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: red-team
  prune: true


